
### saludo
GET http://localhost:8000/

### ver todas las consultas 
GET http://localhost:8000/api/users

### Crear una peli

POST http://localhost:8000/api/user
Content-Type: application/json
    
    {
        "id": "1",
        "nombre": "peli1"
    }

### ELIMINAR 

DELETE http://localhost:8000/delete/7

### ACTUALIZAR

PUT http://localhost:8000/
Content-Type: application/json

    {
        "nombre": "peli1"
    }