
### saludo
GET http://localhost:4040/

### ver todas las consultas 
GET http://localhost:8000/api/pelis

### ver todas las pelis por id
GET http://localhost:8000/api/peli/2

### Crear una peli
POST http://localhost:8000/api/peli
Content-Type: application/json
    
    {
         "id": 1,
        "Titulo": "Breve historia del tiempo",
        "Autor": "Stephen Hawking",
        "Descripcion": "La explicación del universo para todos.",
        "FechaDePublicacion": "1988-04-01",
        "Calificacion": "4",
        "Stock": "25",
        "Categoria": "No Ficción",
        "Precio": "19.99",
        "autor": {
            "id": 17,
            "nombre": "Stephen Hawking"
        },
        "categoria": {
            "id": 1,
            "nombre": "No Ficción"
        }
    }

### ELIMINAR 

DELETE http://localhost:8000/delete/7

### ACTUALIZAR

PUT http://localhost:8000/
Content-Type: application/json

    {
        "nombre": "peli1"
    }



// consula
### ver todas las pelis por genero
GET http://localhost:8000/api/genero/1