
### ver todas las consultas 
GET http://localhost:4040/getallPelis

###
GET http://localhost:4040/SearchByYearPelicula/1997

### consulta 8  Buscar películas con una palabra clave en el título o descripción

GET http://localhost:4040/SearchByClave/Interestelar